version: '3.6'
services:
  service:
    build:
      # context: .
      dockerfile: ./server/Dockerfile
      target: service
    ports:
      - "8000:8000"
    # command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8080
