openapi: 3.0.1
info:
  description: ""
  title: analysis
  version: 1.0.0
servers:
- url: /
paths:
  /predicts/groups:
    post:
      deprecated: false
      description: ""
      parameters: []
      requestBody:
        content:
          application/json:
            example:
              user_id: "0"
              talk_session_id: "0"
            schema:
              $ref: '#/components/schemas/_predicts_groups_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: ""
      security:
      - basic: []
      summary: API
      tags: []
  /test:
    get:
      deprecated: false
      description: ""
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_test_get_200_response'
          description: ""
      security: []
      summary: テストAPI
      tags: []
components:
  schemas:
    _predicts_groups_post_request:
      properties:
        user_id:
          title: user_id
          type: string
        talk_session_id:
          title: talk_session_id
          type: string
      required:
      - talk_session_id
      - user_id
      title: _predicts_groups_post_request
      type: object
    _test_get_200_response:
      example:
        text: hello
      properties:
        text:
          default: hello
          description: テキスト
          title: text
          type: string
      title: _test_get_200_response
      type: object
  securitySchemes:
    basic:
      scheme: basic
      type: http
